# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Addr < Formula
  desc "Look up route origin information from the command-line"
  homepage "https://github.com/thatmattlove/addr"
  version "0.0.3"
  license "BSD-3-Clause-Clear"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.3/addr_0.0.3_darwin_arm64.tar.gz"
      sha256 "601235d7952cf9e8a81b9ba564f31109709e6578091feab8e4cbbbe3959a7b24"

      def install
        bin.install "addr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.3/addr_0.0.3_darwin_amd64.tar.gz"
      sha256 "b5130d174516798606a99ce61a2c7fbe6997ee096de4cc5e32a99a901eff155e"

      def install
        bin.install "addr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.3/addr_0.0.3_linux_armv6.tar.gz"
      sha256 "0765f9ddefee618691ce12649007762b21c719a56b34a932cee28679870512dd"

      def install
        bin.install "addr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.3/addr_0.0.3_linux_amd64.tar.gz"
      sha256 "58b4d4e45f8b81015cb8183c7ff0279515046e89f5c66c924344de54a393d2e8"

      def install
        bin.install "addr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.3/addr_0.0.3_linux_arm64.tar.gz"
      sha256 "638965b6473654afe06aaf659f9976f511d53f3c54238a1d817c69bd9f20c59a"

      def install
        bin.install "addr"
      end
    end
  end
end
