# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Addr < Formula
  desc "Look up route origin information from the command-line"
  homepage "https://github.com/thatmattlove/addr"
  version "0.0.1"
  license "BSD-3-Clause-Clear"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.1/addr_0.0.1_darwin_arm64.tar.gz"
      sha256 "4650aaad8ea558997dfdb802f0b62fe84db37b39ff9ba1d4d5f299ebfad065eb"

      def install
        bin.install "addr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.1/addr_0.0.1_darwin_amd64.tar.gz"
      sha256 "09ae39ef285dba24d5ddddc341ee4f044842533ee129f43400f4c713e1ba72d4"

      def install
        bin.install "addr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.1/addr_0.0.1_linux_amd64.tar.gz"
      sha256 "97a406384dc2952600aefcafdedc24082ec4c7f5c9a9276f8c96929a6d20db63"

      def install
        bin.install "addr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.1/addr_0.0.1_linux_armv6.tar.gz"
      sha256 "8433767360f5bb6892e9a67be862268e6b9e7ecfafddb4abc917ceff9cc1c29a"

      def install
        bin.install "addr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thatmattlove/addr/releases/download/v0.0.1/addr_0.0.1_linux_arm64.tar.gz"
      sha256 "eb4a2f3143de1a3e02b7f325a5d95bdaee68b9222abc26b64257a53e69138ace"

      def install
        bin.install "addr"
      end
    end
  end
end
